
annotations:
  screwdriver.cd/chainPR: true
shared:
  image: node:14
  steps:
    - check: echo $PR_BRANCH_NAME
    - echo: echo `meta get build.jobId`
jobs:
  first:
    requires: [ ~pr, ~commit ]
  second:
    requires: first
